### ISSUE TITLE
Test Train Split Not Making It Manual

### ISSUE THREAD

**Issue by tjdodwell** [digiLab-ai/NuclearEnergy#2]
Going through the example notebook, we see that the test / train split is currently manual.

It would be much nicer if did the Test / Train Split inside the backend. This would allow us to do things like kfold. Here I like the way sklearn do it

```
from sklearn.model_selection import train_test_split

X = df.drop('target', axis=1)
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=23)
```

**Comment by tjdodwell** [comment]
@alexander-mead sorry this was me not understanding you code quite right.

Would be better to have ```train_test_split``` as a target percentage rather than a number of samples.

**Comment by alexander-mead** [comment]
Sorry, I completely missed your first post here for some reason.

Yes, you are absolutely right, `test_train_split` was a misnomer, it has been renamed `test_train_ratio` in the latest version and been changed to be a real number between 0 and 1.
